// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ZtDr63xYnJIoDnYAy-5RfvynnKamlL0',
    appId: '1:626365972343:web:b5510436a2aeb58c7aab72',
    messagingSenderId: '626365972343',
    projectId: 'bannuwool',
    authDomain: 'bannuwool.firebaseapp.com',
    storageBucket: 'bannuwool.appspot.com',
    measurementId: 'G-KGFJMTET8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRa27xDExjo19oztaIZCV4_P7r24i-w3U',
    appId: '1:626365972343:android:d15d50d18945a89f7aab72',
    messagingSenderId: '626365972343',
    projectId: 'bannuwool',
    storageBucket: 'bannuwool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM4YYGtlUUF_V2qHBQYGT-D5Fn8oVFXDo',
    appId: '1:626365972343:ios:8a22ab8cc15ba67c7aab72',
    messagingSenderId: '626365972343',
    projectId: 'bannuwool',
    storageBucket: 'bannuwool.appspot.com',
    iosBundleId: 'com.example.bannuwool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM4YYGtlUUF_V2qHBQYGT-D5Fn8oVFXDo',
    appId: '1:626365972343:ios:9c88f09dcfff39157aab72',
    messagingSenderId: '626365972343',
    projectId: 'bannuwool',
    storageBucket: 'bannuwool.appspot.com',
    iosBundleId: 'com.example.bannuwool.RunnerTests',
  );
}
